# Generated by Django 2.0.7 on 2018-07-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-created'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AddField(
            model_name='services',
            name='content',
            field=models.TextField(default=123, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
