# Generated by Django 2.0.7 on 2018-07-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180723_0446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='Service',
        ),
    ]
